-- MySQL Script generated by MySQL Workbench
-- Sun Feb 15 18:41:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `DNI` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLEADO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `DNI` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `cargo` ENUM('Gerente', 'Recepcionista', 'Limpieza', 'Mantenimiento', 'Director', 'Botones') NOT NULL,
  `EMPLEADO_A_CARGO` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `fk_EMPLEADO_EMPLEADO_idx` (`EMPLEADO_A_CARGO` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_EMPLEADO`
    FOREIGN KEY (`EMPLEADO_A_CARGO`)
    REFERENCES `mydb`.`EMPLEADO` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESERVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RESERVA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RESERVA` (
  `idRESERVA` INT NOT NULL,
  `EMPLEADO_DNI` VARCHAR(45) NOT NULL,
  `fecha_entrada` DATETIME NOT NULL,
  `fecha_salida` DATETIME NOT NULL,
  `estado` ENUM('Pendiente', 'Confirmada', 'Cancelada', 'Check-in', 'Check-out', 'No Show') NOT NULL,
  `CLIENTE_DNI` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRESERVA`),
  INDEX `fk_RESERVA_CLIENTE1_idx` (`CLIENTE_DNI` ASC) VISIBLE,
  INDEX `fk_RESERVA_EMPLEADO1_idx` (`EMPLEADO_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_DNI`)
    REFERENCES `mydb`.`CLIENTE` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_DNI`)
    REFERENCES `mydb`.`EMPLEADO` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FACTURA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FACTURA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FACTURA` (
  `idFACTURA` INT NOT NULL,
  `fecha_emision` DATETIME NOT NULL,
  `RESERVA_idRESERVA` INT NOT NULL,
  PRIMARY KEY (`idFACTURA`),
  INDEX `fk_FACTURA_RESERVA1_idx` (`RESERVA_idRESERVA` ASC) VISIBLE,
  UNIQUE INDEX `RESERVA_idRESERVA_UNIQUE` (`RESERVA_idRESERVA` ASC) VISIBLE,
  CONSTRAINT `fk_FACTURA_RESERVA1`
    FOREIGN KEY (`RESERVA_idRESERVA`)
    REFERENCES `mydb`.`RESERVA` (`idRESERVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HABITACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HABITACION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HABITACION` (
  `idHABITACION` INT NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `precio_noche` DECIMAL(10,2) NOT NULL,
  `estado` ENUM('Disponible', 'Ocupada', 'Sucia', 'Mantenimiento') NOT NULL,
  `planta` VARCHAR(45) NOT NULL,
  `caracteristicas` SET('Wifi', 'Aire Acondicionado', 'Caja Fuerte', 'Minibar', 'Vistas al Mar', 'Jacuzzi', 'TV Satélite') NULL,
  PRIMARY KEY (`idHABITACION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EXTRAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EXTRAS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EXTRAS` (
  `idEXTRAS` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idEXTRAS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESERVA_HABITACION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RESERVA_HABITACION` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RESERVA_HABITACION` (
  `RESERVA_idRESERVA` INT NOT NULL,
  `HABITACION_idHABITACION` INT NOT NULL,
  PRIMARY KEY (`RESERVA_idRESERVA`, `HABITACION_idHABITACION`),
  INDEX `fk_RESERVA_has_HABITACION_HABITACION1_idx` (`HABITACION_idHABITACION` ASC) VISIBLE,
  INDEX `fk_RESERVA_has_HABITACION_RESERVA1_idx` (`RESERVA_idRESERVA` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVA_has_HABITACION_RESERVA1`
    FOREIGN KEY (`RESERVA_idRESERVA`)
    REFERENCES `mydb`.`RESERVA` (`idRESERVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_has_HABITACION_HABITACION1`
    FOREIGN KEY (`HABITACION_idHABITACION`)
    REFERENCES `mydb`.`HABITACION` (`idHABITACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PAGO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PAGO` (
  `idPAGO` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `FACTURA_idFACTURA` INT NOT NULL,
  PRIMARY KEY (`idPAGO`),
  INDEX `fk_PAGO_FACTURA1_idx` (`FACTURA_idFACTURA` ASC) VISIBLE,
  CONSTRAINT `fk_PAGO_FACTURA1`
    FOREIGN KEY (`FACTURA_idFACTURA`)
    REFERENCES `mydb`.`FACTURA` (`idFACTURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EXTRA_ASIGNADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EXTRA_ASIGNADO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EXTRA_ASIGNADO` (
  `RESERVA_HABITACION_RESERVA_idRESERVA` INT NOT NULL,
  `RESERVA_HABITACION_HABITACION_idHABITACION` INT NOT NULL,
  `EXTRAS_idEXTRAS` INT NOT NULL,
  `cantidad` INT NULL,
  INDEX `fk_EXTRA_ASIGNADO_RESERVA_HABITACION1_idx` (`RESERVA_HABITACION_RESERVA_idRESERVA` ASC, `RESERVA_HABITACION_HABITACION_idHABITACION` ASC) VISIBLE,
  INDEX `fk_EXTRA_ASIGNADO_EXTRAS1_idx` (`EXTRAS_idEXTRAS` ASC) VISIBLE,
  PRIMARY KEY (`RESERVA_HABITACION_HABITACION_idHABITACION`, `EXTRAS_idEXTRAS`, `RESERVA_HABITACION_RESERVA_idRESERVA`),
  CONSTRAINT `fk_EXTRA_ASIGNADO_RESERVA_HABITACION1`
    FOREIGN KEY (`RESERVA_HABITACION_RESERVA_idRESERVA` , `RESERVA_HABITACION_HABITACION_idHABITACION`)
    REFERENCES `mydb`.`RESERVA_HABITACION` (`RESERVA_idRESERVA` , `HABITACION_idHABITACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EXTRA_ASIGNADO_EXTRAS1`
    FOREIGN KEY (`EXTRAS_idEXTRAS`)
    REFERENCES `mydb`.`EXTRAS` (`idEXTRAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
